import { Component, signal } from '@angular/core';

import {
  AvAlertComponent,
  AvAlertContentComponent,
  AvAlertDescriptionComponent,
  AvAlertIndicatorComponent,
  AvAlertTitleComponent,
  AvAvatarComponent,
  AvAvatarFallbackComponent,
  AvAvatarImageComponent,
  AvButtonComponent,
  AvCardComponent,
  AvCardContentComponent,
  AvCardDescriptionComponent,
  AvCardFooterComponent,
  AvCardHeaderComponent,
  AvCardTitleComponent,
  AvCheckboxComponent,
  AvCheckboxControlComponent,
  AvCheckboxIndicatorComponent,
  AvCloseButtonComponent,
  AvDescriptionComponent,
  AvDropdownComponent,
  AvDropdownMenuComponent,
  AvDropdownPopoverComponent,
  AvDropdownTriggerDirective,
  AvInputComponent,
  AvInputOtpComponent,
  AvInputOtpGroupComponent,
  AvInputOtpSeparatorComponent,
  AvInputOtpSlotComponent,
  AvKbdAbbrComponent,
  AvKbdComponent,
  AvKbdContentComponent,
  AvLabelComponent,
  AvLinkComponent,
  AvListBoxComponent,
  AvListBoxItemComponent,
  AvListBoxSectionComponent,
  AvMenuItemComponent,
  AvMenuSectionComponent,
  AvRadioComponent,
  AvRadioControlComponent,
  AvRadioGroupComponent,
  AvRadioIndicatorComponent,
  AvSeparatorComponent,
  AvSliderComponent,
  AvSliderFillComponent,
  AvSliderOutputComponent,
  AvSliderThumbComponent,
  AvSliderTrackComponent,
  AvSpinnerComponent,
  AvSurfaceComponent,
  AvSwitchComponent,
  AvSwitchContentComponent,
  AvSwitchControlComponent,
  AvSwitchThumbComponent,
  AvTabsComponent,
  AvTabsIndicatorComponent,
  AvTabsListComponent,
  AvTabsPanelComponent,
  AvTabsTabComponent,
} from '@avesra/angular';

import { AppIconComponent } from '../../../../components/app-icon/app-icon.component';

@Component({
  selector: 'app-home-components-panel',
  imports: [
    AppIconComponent,
    AvAlertComponent,
    AvAlertContentComponent,
    AvAlertDescriptionComponent,
    AvAlertIndicatorComponent,
    AvAlertTitleComponent,
    AvAvatarComponent,
    AvAvatarFallbackComponent,
    AvAvatarImageComponent,
    AvButtonComponent,
    AvCardComponent,
    AvCardContentComponent,
    AvCardDescriptionComponent,
    AvCardFooterComponent,
    AvCardHeaderComponent,
    AvCardTitleComponent,
    AvCheckboxComponent,
    AvCheckboxControlComponent,
    AvCheckboxIndicatorComponent,
    AvCloseButtonComponent,
    AvDescriptionComponent,
    AvDropdownComponent,
    AvDropdownMenuComponent,
    AvDropdownPopoverComponent,
    AvDropdownTriggerDirective,
    AvInputComponent,
    AvInputOtpComponent,
    AvInputOtpGroupComponent,
    AvInputOtpSeparatorComponent,
    AvInputOtpSlotComponent,
    AvKbdAbbrComponent,
    AvKbdComponent,
    AvKbdContentComponent,
    AvLabelComponent,
    AvLinkComponent,
    AvListBoxComponent,
    AvListBoxItemComponent,
    AvListBoxSectionComponent,
    AvMenuItemComponent,
    AvMenuSectionComponent,
    AvRadioComponent,
    AvRadioControlComponent,
    AvRadioGroupComponent,
    AvRadioIndicatorComponent,
    AvSeparatorComponent,
    AvSliderComponent,
    AvSliderFillComponent,
    AvSliderOutputComponent,
    AvSliderThumbComponent,
    AvSliderTrackComponent,
    AvSpinnerComponent,
    AvSurfaceComponent,
    AvSwitchComponent,
    AvSwitchContentComponent,
    AvSwitchControlComponent,
    AvSwitchThumbComponent,
    AvTabsComponent,
    AvTabsIndicatorComponent,
    AvTabsListComponent,
    AvTabsPanelComponent,
    AvTabsTabComponent,
  ],
  templateUrl: './components-panel.component.html',
  styleUrl: './components-panel.component.scss',
})
export class HomeComponentsPanelComponent {
  readonly notifications = signal(true);
  readonly otp = signal('4320');
  readonly stateLabel = signal('Select one');

  readonly avatars = [
    { name: 'Blue', src: '/images/gradients/gradient-blue-cyan.png' },
    { name: 'Green', src: '/images/gradients/gradient-cyan-blue-purple.png' },
    { name: 'Purple', src: '/images/gradients/gradient-purple-violet.png' },
    { name: 'Orange', src: '/images/gradients/gradient-warm-orange-yellow-red.png' },
    { name: 'Red', src: '/images/gradients/gradient-pink-magenta.png' },
  ];

  readonly communities = [
    {
      name: 'Indie Hackers',
      members: '148 members',
      by: 'By John',
      cover: '/images/objects/object-yellow-mushroom-lamp.png',
      avatar: '/images/gradients/gradient-pink-magenta.png',
    },
    {
      name: 'AI Builders',
      members: '362 members',
      by: 'By Martha',
      cover: '/images/avatars/avatar-woman-orange-jacket.png',
      avatar: '/images/gradients/gradient-blue-cyan.png',
    },
  ];

  selectState(label: string): void {
    this.stateLabel.set(label);
  }
}
